language: java

dist: bionic

jdk:
  - openjdk8

env:
  global:
    - MOZ_HEADLESS=1

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3 python3-pip

install:
  - mvn clean install -Dwebdriver.gecko.driver=$TRAVIS_BUILD_DIR/cucumber-audit-scenarios/src/test/resources/geckodriver

before_deploy:
  - git clone https://github.com/multicatch/multicatch.github.io.git
  - mkdir -p multicatch.github.io/cucumber-audit/$TRAVIS_BRANCH
  - cp -r cucumber-audit-scenarios/target/cucumber/cucumber-html-reports multicatch.github.io/cucumber-audit/$TRAVIS_BRANCH

deploy:
  - provider: pages
    repo: multicatch/multicatch.github.io
    target_branch: master
    skip-cleanup: true
    github-token:
      secure: "7OgFdPQ5XcKpY8JJbpM5TO4PM7pmzXE6yv65tYw355wdCPDqr/RajqzkEhDRFvlaLYbQFlGnkHbuoo6WCkAI4g4wnNKVHeQdnfAtYsaI6pm6Wcxhgs+IvuBTACf9InryHGM+ZTmGC/F4A3ZYJhrP3jP436HD3bOUBnDZkXbRmnS9LiE1xlnBKHLa0mAMVtf0aSk+kkZXjyB+d4VRbNu+KfJUowojvDR5jgwLR5SnOi64bZbNEDfPZN+zJy2jzD4Zi8zGOHwkJR6dFIYGGzLUSA1pbd8siOop8pLsexFLQ3bKJAOOZ4WwMzgysai6s6dk+CoaK1BJwteEEvqTUuPbOrRO52jo4KlS8cQiAnmNI8pB+Lgyfm5AXOvk3YKHlBIJO+fkZam2M1ovMk/QD09kJKFsNeg3mNh10XFxb7ajQkU8m5KZI4jVJC8fztQvhOoTAFDneZlRIQM1KZ0mWuzGymepAPYVPoGpb6hQt7X9N5zKMLcOYhUhZcta6Fy6Q92078BPPylXaT+bgkdWHgv3daf+9ow0+M3xL8mt9iGhHQ5A8brMNN9zsBaL9kgjR13GWCkBE0zwCjNjdazWofgfbD5P0iyU+WoP5xdhldJtfjQ6AWXBMAlv2dF8KbBB+VGJ2eRDnCPwF1E6n7lgw/7v12XhAvA8UUYtJr3Ks9tCQ6I="
    keep-history: true
    local-dir: "multicatch.github.io"
    verbose: true
    on:
      all_branches: true