language: java

dist: bionic

jdk:
  - openjdk8

env:
  global:
    - MOZ_HEADLESS=1
    - webdriver.gecko.driver=$TRAVIS_BUILD_DIR/cucumber-audit-scenarios/src/test/resources/geckodriver

addons:
  firefox: latest

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3 python3-pip

install:
  - mvn clean install