language: java

dist: bionic

jdk:
  - openjdk8

env:
  global:
    - MOZ_HEADLESS=1

addons:
  firefox: latest
  chrome: stable
  sonarcloud:
    organization: "multicatch"
    token:
      secure: "f81XdOCO+9gBNlh3Av1BW1eeS042dxVn4XdIvODx2H1Lle9k0TXmJOCC9pt45kQofiOQP0bCCGFT7Vh4LQayu2mKno4LLhMSXfPR5VNY1VICTa9l0OGQoGxj9OsfwHD2MC6iQGnDZeDBh2HvQ86I7cumzfbphcaK2gEHopkqn3UHt/b0r+nPbcGYm6J+/WnFZ4EaYaxdATrJlz7gDfpLbyJH2ccqLzaT+dP3SkTIYWe/tepn9b44w6vLK6J/GCJwgVJHCg/UxeXeWTdy8FJChKkSdNzxivLv2fF4QcP6ONlbFvS3J8AVZMB/PTOXBBsAJQf1K8jjjRRL2ZLJaX40/6Z8eE0Va5ZR7k1FvX2B/frUH33gUpBAoe+JBUO2eM9Np71pego4xm9d5eyzVvOiTVN/X3X33+sVlyeXOkUCSEZpDxRIncc7Spry4oHdyxbmLsekqRWQpw220Wzrn5XdUNQculxlUNdx7aS3d0vGiRmBbbeWbGRrXG12bAs0OdXykTuRgoc0mH/54WvpXuSeGfvE6BNZOwbitntXSzE/sEfadcaWjpFjb+19duUbFqzJmG4PhMKVtTs6MbnnDozn0aJuyHmbWDYWogyBySiUdfd0hACwlHkLm0I8FYiGQJD11VbNL4SzJy0wmircQPVcGWniynDrE974TmFJmm/kP7M="

cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3 python3-pip

before_script:
  - git fetch origin +refs/heads/master:refs/remotes/origin/master

script:
  - mvn clean install -Dwebdriver.gecko.driver=$TRAVIS_BUILD_DIR/cucumber-audit-scenarios/src/test/resources/geckodriver -Dwebdriver.chrome.driver=$TRAVIS_BUILD_DIR/cucumber-audit-stepdefs/src/test/resources/chromedriver
  - mvn jacoco:report sonar:sonar -Dsonar.projectKey=multicatch_cucumber-audit

before_deploy:
  - git clone https://github.com/multicatch/multicatch.github.io.git
  - mkdir -p multicatch.github.io/cucumber-audit/$TRAVIS_BRANCH
  - cp -r cucumber-audit-scenarios/target/cucumber/cucumber-html-reports multicatch.github.io/cucumber-audit/$TRAVIS_BRANCH

deploy:
  - provider: pages
    repo: multicatch/multicatch.github.io
    target_branch: master
    skip-cleanup: true
    github-token:
      secure: "3h3LbUUuMcUD8c5txucxeRjWA8+f+HRqtFsmztCy1uCLBPGKPHPqrFvWRawaS9y83JTHngvG1b/gXTkPRsRJ7rUL9EjC+g6TU+HFzpu6IhO9/uAWcFh9++JD+kzhUuQc+3CFANJBxYajCI7/TtT/ecIckUZ066gY+qK3WXZQ0+SB3f15tiII+ead19w5nftenbZYa7+ADO5ZVPElAtshMaLr/vVwYVK2xT5rYep3wzALTCRHkNrzwp9CYcgGJaHkzO+khT/qprhb5xlES9ynhQwDmDmVyu0NxDpUfw9QhiYI+SIFw279S72lZKTH5aSxHF12zdt3Df0aI2psUAPW+RRWGWf8Yc0qwU5XlgAtaZNIFoSr5NllwhUrHpHpEZLsDU3QVF3i1ALh7WORrc5EoH6tqW2pzyGxYl4yJgZqRYTDrFVjvKg+hbO86j20J3cKKxaTTxhZCafSE9azUh6hbGikdF40Tku/tEWFDTU39L7RFl9P/L2MuHNdR5PSf0CFkY/UGfDEVVia2mjC0GxUSfl94S5OPJg/0jAzoO/YUBL20ipJIZbH5Hyk3rOmpC3dkHvrRH/9DmShlU+A/JWfTA/PF6gRK0tijYqkJPq9lLjHrui69FFDHuvWEVh2C3OFN6Npi3B1oYGPnWOVrBx/t/tL0QnMTbUaG9rIKi8/MYM="
    keep-history: true
    local-dir: "multicatch.github.io"
    verbose: true
    on:
      all_branches: true
