language: java

dist: bionic

jdk:
  - openjdk8

services:
  - docker

env:
  global:
    - MOZ_HEADLESS=1
    - secure: "T/HE96dRzTQtqBVs5DgoZg7WRALrrzVeHDe3cgQTQTFCyIVVRCOP3Alwv8jDYfNNASrSYIUzTtGme2Xs4jXMHjuyuk4bp3tFAAVwavihPTCyBAFuEm7CsRcUEeX85b8jMVp19To0a5FrmrD27XZqes2EwbKEi8aTomkvgT5gMnB/jH6SQZKd/lN1gst37y3F2hue4Rq5Krh07KvcCmmPcXNMGrtKg639tD2YbWqciw26PQU/5kjF8RccjeqOds8U+h+bNc3WgnqBbDX3qbt0Pjef0froFeD5jUcrxVjctrkvZe2TJgbN2C1izeN3mt2gcHTxasG5mtIQBJTBA68JQuci2fZDSJtP8CEsTcbZdRfel6OCj9bxZ3CM04l0WhUfD1taRMBnBGxL8H2SAw46bMlipMm8Wl1vk8hK3IPyTBrXPgIAYOSQhQe0FHOZTrbQMZJWa1JbO2mdDehpFvlUKtzcg7N6A+yTzdCFq/iTp+7DyUAfTu+I3ODycNorPhciBzf0Bisu8Dx/TW5B2Xm8SuYUY7l7pPxndCbaHol9HZ9xvWMUfWs/D3T7NzeknG+WM4Kvw0olFqsBxzIM5d6e7HRE7Rg3jQGLRs5H2rC7m+QNn/FJqtnphYTiRps4zXumWSyyqVS/Iqkf6Vm1Pt82PzOEtfvfYmo96vbL4qoRGPU="
    - secure: "1lu6JGyqczAVgz6FfKCEnnHJXV8Rd9U6v/Hgs6plo0cOztelKB5LgPuJdvF8UUvzwkYx05yyJg4fGpLCFHGhWbnlGEiLxxdNcw9rKctwF/23HYDzv1EzNbtIkiUz+9jp9yrjkeQmN9Gp/lqu5nW5BVHrPkTfTv23P/liHPar3zIhS+T9YVdLfS10LmyMmHv8ikce0RlZ75l9PuJ90/afEsb2rmg+YTFcOxC+P3zCO8jClyl03u++/wNhj3GKA/6SCirL0v7CME9E5/6UlZaPh4Sb+/ByYt0CJyAX2vo6PkzsSAFkXIl00O8HasrxDS/1NDbcUhUFcEAFhO1YEQdRLed3D25Rngqs1tBMN5X/kAKBB9eVPzEy87z91C6lFpVW+ISOn/IJQonW41B47gcHsUpOyOcVLsg2Uy00UhNXrXgJ9/StVJbdsymg7pwDPiJ0XrRYYwsSuCfZRFNFUe9SJ/HiSwoIlWEDblav7jj/984ZqlNuScrxPZCD3veZJ1cvnM7Jyf3wZtPoXtX9NSpctmZE540A0cG8kSKeetrzH/1cbVQancRD61fC3EXZJDiV5PN7OUs2y4nukk5L35/Ac8ffVEhs2Ioc84BxnBB7uYInaKIXAVAWFro/Tn0ttsvS3kkaoBH+R3Ix6A/vfoPmDYerdmPIO9JpKDgeg/so154="
    - secure: "3PV1CotbvN8ja2bgVeNs9rturulyvF5inzltmVcCX6lu5NNd0aGxYqqQYeyno5CdfVXpBgE5sMZwPCpi2rFO0M6upmDJI5WgT3uqtCb6sm+gdNFKPvQjbzkYcu8fwpJIxEu9HF2sVKY+/bnJ26XHL6BT6HAJDHnYZ4RKPP0qmGFyJ/IfhlxiI9gLOMbjbpa1gZDIoz3kFQCDX5EfiPKvJCO/kQuD6YXdfWdvDSTA3fbLIXU7GcQFusO1HiNvrxa90fnsrAVQkPS39IPF06//u0pH79b9JumZ4Pfcdpt4XP+fNmfARaBnvGsW8zf6xg2KbsDyAErdIbJ6XvHAAZXg3ZV6z9lpz3mxE/oGOpGgQAsCyjrquomdK6kiDOdyvpDTd4guTy4yUtRHEtFyPX6SccUOMavSmOlnoOFvSdBXKjntTsjgoZ5zbQ7ZCk2HFZ69oydyBKrC0kjoCwf9dEL6BjOjCLaUPwvSG2uTY03Jo/2/i68MlmfEKItuvnHNMOKp2yYvhXZRW32ezhqWyPiCmCRMdFfFRiVQzmIGuj4qo/q5oziFwFR7kgpJTO3KnNJhhQdgOSghbUFyNQzTvPCQEnjQtXqjF+nVcoTnsc+aNut+hgP5IR135r7u/OP6djdozxuJRxtPhd7+5s/LT1VS0cTJZz9Eln9chJIcsC6+caI="
    - secure: "l0zHKhvGGsRR9JoufHqSBon4YNd0Brldw/GDKmJFpOmqEP9woxW68JgLdfmXdhyXfRHX7vuRTYnvlj/ZFzgTQ8Il/MOtqw0QDn7QIHWbQtm+pSp8sMQEeQ12AD6rCirm3tPNCfdwBjJnC4m3qNqheD/AQvWaCnRuPqvxPpyZAQ4ko2e0U5F2q82tO0J0/NlUW9LzXLvR9jH2XOdDEC97AEtxkeX8n9dSd0uXiCsQQ3H+JjA2g0fkQ7cgLOnJOx+I4Ey/odk2ghfLcJ5NkRGMY5Dpp42fxy2W+ZjVv9SYi+na1JAn4FZVeGP2yWJ9eHx//P1SzKY9BI292Qys2myPjDwYiiN0Jn/DjEzql9EIj+CE/uYvFNKmoz+CSzPu5McYGlcXkSw82H3KZK40dkWfGaytihJAhm/8Jo5pAF1Hu8XbLkFe77q0UxirkBQRF76IwlophS4hxUxlKn3w3L5M4cRmsF2/LTlj0YYHY8BiSFeZPsBvUFdtv/mWdc/951ykGryWtdsF64GmyeqsUy15gb3ti5lZf1+j6nFVTrljKcMnWE75yhMDdjRrOqzuzykW2m+k+oEK0eJGoGG8C6TPqf0zuRyt5h0eb8R5QFCp+bV256KJ0SrxYGtSow+IcK1AxpDSz5tCpmmNr9jT2tQ0GNumf77WTM9jfrXleHvGjiY="

addons:
  firefox: latest
  chrome: stable
  sonarcloud:
    organization: "multicatch"
    token:
      secure: "f81XdOCO+9gBNlh3Av1BW1eeS042dxVn4XdIvODx2H1Lle9k0TXmJOCC9pt45kQofiOQP0bCCGFT7Vh4LQayu2mKno4LLhMSXfPR5VNY1VICTa9l0OGQoGxj9OsfwHD2MC6iQGnDZeDBh2HvQ86I7cumzfbphcaK2gEHopkqn3UHt/b0r+nPbcGYm6J+/WnFZ4EaYaxdATrJlz7gDfpLbyJH2ccqLzaT+dP3SkTIYWe/tepn9b44w6vLK6J/GCJwgVJHCg/UxeXeWTdy8FJChKkSdNzxivLv2fF4QcP6ONlbFvS3J8AVZMB/PTOXBBsAJQf1K8jjjRRL2ZLJaX40/6Z8eE0Va5ZR7k1FvX2B/frUH33gUpBAoe+JBUO2eM9Np71pego4xm9d5eyzVvOiTVN/X3X33+sVlyeXOkUCSEZpDxRIncc7Spry4oHdyxbmLsekqRWQpw220Wzrn5XdUNQculxlUNdx7aS3d0vGiRmBbbeWbGRrXG12bAs0OdXykTuRgoc0mH/54WvpXuSeGfvE6BNZOwbitntXSzE/sEfadcaWjpFjb+19duUbFqzJmG4PhMKVtTs6MbnnDozn0aJuyHmbWDYWogyBySiUdfd0hACwlHkLm0I8FYiGQJD11VbNL4SzJy0wmircQPVcGWniynDrE974TmFJmm/kP7M="

cache:
  directories:
    - $HOME/.m2

before_script:
  - git fetch origin +refs/heads/master:refs/remotes/origin/master
  - chmod u+x ./download_drivers.sh && ./download_drivers.sh

script:
  - mvn clean install -Dwebdriver.gecko.driver=$TRAVIS_BUILD_DIR/webdrivers/geckodriver -Dwebdriver.chrome.driver=$TRAVIS_BUILD_DIR/webdrivers/chromedriver
  - mvn jacoco:report sonar:sonar -Dsonar.projectKey=multicatch_cucumber-audit

after_script:
  - git clone https://github.com/multicatch/multicatch.github.io.git
  - mkdir -p multicatch.github.io/cucumber-audit/$TRAVIS_BRANCH
  - cp -r cucumber-audit-scenarios/target/cucumber/cucumber-html-reports multicatch.github.io/cucumber-audit/$TRAVIS_BRANCH

deploy:
  - provider: pages
    repo: multicatch/multicatch.github.io
    target_branch: master
    skip-cleanup: true
    github-token:
      secure: "3h3LbUUuMcUD8c5txucxeRjWA8+f+HRqtFsmztCy1uCLBPGKPHPqrFvWRawaS9y83JTHngvG1b/gXTkPRsRJ7rUL9EjC+g6TU+HFzpu6IhO9/uAWcFh9++JD+kzhUuQc+3CFANJBxYajCI7/TtT/ecIckUZ066gY+qK3WXZQ0+SB3f15tiII+ead19w5nftenbZYa7+ADO5ZVPElAtshMaLr/vVwYVK2xT5rYep3wzALTCRHkNrzwp9CYcgGJaHkzO+khT/qprhb5xlES9ynhQwDmDmVyu0NxDpUfw9QhiYI+SIFw279S72lZKTH5aSxHF12zdt3Df0aI2psUAPW+RRWGWf8Yc0qwU5XlgAtaZNIFoSr5NllwhUrHpHpEZLsDU3QVF3i1ALh7WORrc5EoH6tqW2pzyGxYl4yJgZqRYTDrFVjvKg+hbO86j20J3cKKxaTTxhZCafSE9azUh6hbGikdF40Tku/tEWFDTU39L7RFl9P/L2MuHNdR5PSf0CFkY/UGfDEVVia2mjC0GxUSfl94S5OPJg/0jAzoO/YUBL20ipJIZbH5Hyk3rOmpC3dkHvrRH/9DmShlU+A/JWfTA/PF6gRK0tijYqkJPq9lLjHrui69FFDHuvWEVh2C3OFN6Npi3B1oYGPnWOVrBx/t/tL0QnMTbUaG9rIKi8/MYM="
    keep-history: true
    local-dir: "multicatch.github.io"
    verbose: true
    on:
      all_branches: true
  - provider: script
    script: bash maven_deploy.sh
    on:
      branch: develop
