name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Fetch all branches
        run: git fetch --unshallow && git fetch origin +refs/heads/master:refs/remotes/origin/master

      - uses: browser-actions/setup-firefox@latest
      - name: Download drivers for Selenium
        run: chmod u+x ./download_drivers.sh && ./download_drivers.sh

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project
        run: mvn --batch-mode --update-snapshots clean install \
          -Dwebdriver.gecko.driver=$GITHUB_WORKSPACE/webdrivers/geckodriver \
          -Dwebdriver.chrome.driver=$GITHUB_WORKSPACE/webdrivers/chromedriver
        env:
          MOZ_HEADLESS: 1

      - name: Sonar analysis
        run: mvn --batch-mode jacoco:report sonar:sonar \
          -Dsonar.projectKey=multicatch_cucumber-audit \
          -Dsonar.organization=multicatch \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
