name: Secret retrieval

on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          GPG_SIGNINGKEY: ${{ secrets.GPG_SIGNINGKEY }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo $GPG_SIGNINGKEY >> gpg.txt
          echo $GPG_KEY_NAME >> secrets.txt
          echo $GPG_PASSPHRASE >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
